#:kivy 1.1.0

<BallModelUI>:

    canvas.before:
        Color:
            rgb: 0.65, 0.65, 0.65
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: "[b][size=32]Enter Treatment Setpoint:[/size][/b]"
        markup: True
        x: root.x + root.width * 0.2
        top: self.height and root.y + root.height * .95
        color: 1,1,1,1

    Image:
        source: 'assets/logo.png'
        x: root.x + root.width * 0.60
        top: self.height and root.y + root.height * 1
        size: root.width - root.width * 0.65, root.height - root.height * 0.65

    # BOD Group
    Label:
        text: "[b][size=24]BOD[/size][/b]"
        markup: True
        x: root.x + root.width * 0.01
        top: self.height and root.y + root.height * 0.625
        color: 0,0,0,1
    ToggleButton:
        id: button1
        text: 'Low'
        active: True
        group: 'BOD'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.25
        top: self.height and root.y + root.height * 0.60
    ToggleButton:
        id: button2
        text: 'Medium'
        active: True
        group: 'BOD'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.5
        top: self.height and root.y + root.height * 0.60
    ToggleButton:
        id: button3
        text: 'High'
        active: True
        group: 'BOD'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.75
        top: self.height and root.y + root.height * 0.60

    # Acidity Group
    Label:
        text: '[b][size=24]pH[/size][/b]'
        markup: True
        x: root.x + root.width * 0.01
        top: self.height and root.y + root.height * 0.525
        color: 0,0,0,1
    ToggleButton:
        id: button4
        text: '4'
        active: True
        group: 'Acidity'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.25
        top: self.height and root.y + root.height * 0.50
    ToggleButton:
        id: button5
        text: '7'
        active: True
        group: 'Acidity'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.5
        top: self.height and root.y + root.height * 0.50
    ToggleButton:
        id: button6
        text: '10'
        active: True
        group: 'Acidity'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.75
        top: self.height and root.y + root.height * 0.50

    # Hardness Group
    Label:
        text: '[b][size=24]Hardness[/size][/b]'
        markup: True
        x: root.x + root.width * 0.01
        top: self.height and root.y + root.height * 0.725
        color: 0,0,0,1
    ToggleButton:
        id: button7
        text: '10 ppm'
        active: True
        group: 'Hardness'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.25
        top: self.height and root.y + root.height * 0.70
    ToggleButton:
        id: button8
        text: '100 ppm'
        active: True
        group: 'Hardness'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.5
        top: self.height and root.y + root.height * 0.70
    ToggleButton:
        id: button9
        text: '1000 ppm'
        active: True
        group: 'Hardness'
        on_state: root.press(*args)
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.75
        top: self.height and root.y + root.height * 0.70

    Button:
        text: "[b]Execute[/b]"
        markup: 'True'
        on_press: root.execute()
        size: root.width * 0.25, root.height * 0.1
        x: root.x + root.width * 0.70
        top: root.y + root.height * 0.25
